### ISSUE TITLE
Problem connecting to operator "Swisscom"(a swiss mobile operator)

### ISSUE THREAD

**Issue by weishaaan** [twitter/cloudhopper-smpp#131]
Hello, First, thanks a lot for this library. It works really good for 
(1) a server i found on line (https://github.com/MavoCz/smscsim) 
(2) a server of my company
The log file shows as following:

`
2017-04-19 18:38:57.524  INFO 16126 --- [           main] com.sicap.cloud.dmc.DmcCloudApplication  : Starting DmcCloudApplication on Wei.local with PID 16126 (/Users/sicap/projects/prd_dmc_cloud/dmc-cloud/target/classes started by sicap in /Users/sicap/projects/prd_dmc_cloud/dmc-cloud)
2017-04-19 18:38:57.531  INFO 16126 --- [           main] com.sicap.cloud.dmc.DmcCloudApplication  : The following profiles are active: wsh
2017-04-19 18:38:57.578  INFO 16126 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@431d1474: startup date [Wed Apr 19 18:38:57 CEST 2017]; root of context hierarchy
2017-04-19 18:38:58.456  INFO 16126 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'templateResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=iosProtocolApplication; factoryMethodName=templateResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/sicap/protocols/ios/IosProtocolApplication.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=dmcCloudApplication; factoryMethodName=templateResolver; initMethodName=null; destroyMethodName=(inferred); defined in com.sicap.cloud.dmc.DmcCloudApplication]
2017-04-19 18:38:58.457  INFO 16126 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'templateEngine' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=iosProtocolApplication; factoryMethodName=templateEngine; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/sicap/protocols/ios/IosProtocolApplication.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=dmcCloudApplication; factoryMethodName=templateEngine; initMethodName=null; destroyMethodName=(inferred); defined in com.sicap.cloud.dmc.DmcCloudApplication]
2017-04-19 18:38:58.519  INFO 16126 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
2017-04-19 18:38:58.819  INFO 16126 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [class org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$721e9461] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-04-19 18:38:59.114  INFO 16126 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 9000 (http)
2017-04-19 18:38:59.124  INFO 16126 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2017-04-19 18:38:59.125  INFO 16126 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.0.30
2017-04-19 18:38:59.189  INFO 16126 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-04-19 18:38:59.189  INFO 16126 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1615 ms
2017-04-19 18:38:59.414  INFO 16126 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2017-04-19 18:38:59.417  INFO 16126 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-04-19 18:38:59.418  INFO 16126 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2017-04-19 18:38:59.418  INFO 16126 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2017-04-19 18:38:59.418  INFO 16126 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]
2017-04-19 18:38:59.501  INFO 16126 --- [           main] o.s.ws.soap.saaj.SaajSoapMessageFactory  : Creating SAAJ 1.3 MessageFactory with SOAP 1.1 Protocol
2017-04-19 18:38:59.685  INFO 16126 --- [           main] o.a.c.w.s.f.ReflectionServiceFactoryBean : Creating Service {http://webservice.soapapi.soapserver.connector.software.swapcom.com}SoapserverPortTypeService from class com.sicap.cloud.dmc.xms.service.MMGSoapServer.soapapi.webservice.SoapserverPortType
2017-04-19 18:39:00.372  INFO 16126 --- [           main] c.s.c.dmc.xms.service.SmsAndMmsService   : Loading appropriate SMS Sender Service for the DMC Cloud
2017-04-19 18:39:00.372  INFO 16126 --- [           main] c.s.c.dmc.xms.service.SmsAndMmsService   : The MMG has been chosen as the default SMS sender for the DMC Cloud
2017-04-19 18:39:00.593  INFO 16126 --- [           main] c.c.smpp.impl.DefaultSmppSession         : sync send PDU: (bind_transceiver: 0x00000021 0x00000009 0x00000000 0x00000001) (body: systemId [gdefo] password [gdefo] systemType [] interfaceVersion [0x34] addressRange (0x00 0x00 [])) (opts: )
2017-04-19 18:39:00.599  INFO 16126 --- [           main] c.c.smpp.impl.DefaultSmppSession         : write bytes: [00000021000000090000000000000001676465666f00676465666f000034000000]
2017-04-19 18:39:00.606  INFO 16126 --- [   china mobile] c.c.smpp.impl.DefaultSmppSession         : read bytes: [00000021800000090000000000000001636c6f7564686f70706572000210000134]
2017-04-19 18:39:00.607  INFO 16126 --- [   china mobile] c.c.smpp.impl.DefaultSmppSession         : received PDU: (bind_transceiver_resp: 0x00000021 0x80000009 0x00000000 0x00000001 result: "OK") (body: systemId [cloudhopper]) (opts: (sc_interface_version: 0x0210 0x0001 [34]))
2017-04-19 18:39:00.611  INFO 16126 --- [           main] c.s.c.d.x.service.SMPPConnectorService   : Loading SMPP Connector Service for the DMC Cloud
2017-04-19 18:39:00.746  INFO 16126 --- [           main] c.s.c.dmc.setting.services.DRBService    : Initializing DRB Cache
2017-04-19 18:39:00.748  INFO 16126 --- [           main] c.s.c.dmc.setting.services.DRBService    : Loading Database of definitions...
2017-04-19 18:39:00.750  INFO 16126 --- [           main] c.s.c.dmc.setting.cache.DRBCacheManager  : Untar of DRB Archive disabled - Going straight to the loading of the DB into the Cache
2017-04-19 18:39:02.123  INFO 16126 --- [           main] c.s.c.dmc.setting.services.DRBService    : DRB cache initialized
2017-04-19 18:39:02.132  INFO 16126 --- [           main] c.s.c.d.xms.service.SmsAckCacheService   : Initializing ACK Cache
2017-04-19 18:39:02.142  INFO 16126 --- [           main] o.a.c.w.s.f.ReflectionServiceFactoryBean : Creating Service {http://webservice.soapapi.soapserver.connector.software.swapcom.com}SoapserverPortTypeService from class com.sicap.cloud.dmc.xms.service.MMGSoapServer.soapapi.webservice.SoapserverPortType
2017-04-19 18:39:02.319  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@431d1474: startup date [Wed Apr 19 18:38:57 CEST 2017]; root of context hierarchy
2017-04-19 18:39:02.372  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/specifications/model/{imei}],methods=[GET]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.setting.controllers.DeviceInfoController.model(java.lang.String)
2017-04-19 18:39:02.373  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/specifications/{imei}],methods=[GET]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.setting.controllers.DeviceInfoController.allInfo(java.lang.String)
2017-04-19 18:39:02.373  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/specifications/brand/{imei}],methods=[GET]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.setting.controllers.DeviceInfoController.brand(java.lang.String)
2017-04-19 18:39:02.374  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/format/data/],methods=[POST]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.setting.controllers.GetSettingController.data(com.sicap.cloud.dmc.setting.entity.SettingAPN,java.lang.String)
2017-04-19 18:39:02.374  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/format/mms/],methods=[POST]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.setting.controllers.GetSettingController.mms(com.sicap.cloud.dmc.setting.entity.SettingAPN)
2017-04-19 18:39:02.374  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/format/wap/],methods=[POST]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.setting.controllers.GetSettingController.wap(com.sicap.cloud.dmc.setting.entity.SettingAPN)
2017-04-19 18:39:02.374  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/format/wlan/],methods=[POST]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.setting.controllers.GetSettingController.wlan(com.sicap.cloud.dmc.setting.entity.SettingWlan)
2017-04-19 18:39:02.377  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/help/manual/data/{brand}/{model}/{language}],methods=[GET]}" onto public java.lang.String com.sicap.cloud.dmc.setting.controllers.HelpController.getDataManualHelp(java.lang.String,java.lang.String,java.lang.String)
2017-04-19 18:39:02.377  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/help/manual/inject/data/{brand}/{model}/{language}],methods=[POST]}" onto public java.lang.String com.sicap.cloud.dmc.setting.controllers.HelpController.getInjectedDataManualHelp(java.lang.String,java.lang.String,java.lang.String,com.sicap.cloud.dmc.setting.entity.APN)
2017-04-19 18:39:02.377  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/help/manual/xml/mms/{brand}/{model}/{language}],methods=[GET]}" onto public java.lang.String com.sicap.cloud.dmc.setting.controllers.HelpController.getXMLMMSManualHelp(java.lang.String,java.lang.String,java.lang.String)
2017-04-19 18:39:02.377  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/help/manual/wlan/{brand}/{model}/{language}],methods=[GET]}" onto public java.lang.String com.sicap.cloud.dmc.setting.controllers.HelpController.getWlanManualHelp(java.lang.String,java.lang.String,java.lang.String)
2017-04-19 18:39:02.377  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/help/manual/wap/{brand}/{model}/{language}],methods=[GET]}" onto public java.lang.String com.sicap.cloud.dmc.setting.controllers.HelpController.getWapManualHelp(java.lang.String,java.lang.String,java.lang.String)
2017-04-19 18:39:02.377  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/help/manual/mms/{brand}/{model}/{language}],methods=[GET]}" onto public java.lang.String com.sicap.cloud.dmc.setting.controllers.HelpController.getMmsManualHelp(java.lang.String,java.lang.String,java.lang.String)
2017-04-19 18:39:02.378  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/help/manual/inject/mms/{brand}/{model}/{language}],methods=[POST]}" onto public java.lang.String com.sicap.cloud.dmc.setting.controllers.HelpController.getInjectedMmsManualHelp(java.lang.String,java.lang.String,java.lang.String,com.sicap.cloud.dmc.setting.entity.APN)
2017-04-19 18:39:02.378  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/help/postota/{brand}/{model}/{language}],methods=[GET]}" onto public java.lang.String com.sicap.cloud.dmc.setting.controllers.HelpController.getPostOTAHelp(java.lang.String,java.lang.String,java.lang.String)
2017-04-19 18:39:02.379  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/images/device/{brand}/{model}],methods=[GET]}" onto public org.springframework.http.ResponseEntity<byte[]> com.sicap.cloud.dmc.setting.controllers.ImagesController.getDeviceImage(java.lang.String,java.lang.String) throws java.io.IOException
2017-04-19 18:39:02.379  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/images/brand/{brand}],methods=[GET]}" onto public org.springframework.http.ResponseEntity<byte[]> com.sicap.cloud.dmc.setting.controllers.ImagesController.getBrandImage(java.lang.String) throws java.io.IOException
2017-04-19 18:39:02.379  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/images/postota/{brand}/{model}],methods=[GET],produces=[image/jpeg]}" onto public org.springframework.http.ResponseEntity com.sicap.cloud.dmc.setting.controllers.ImagesController.getPostOTAImage(java.lang.String,java.lang.String) throws com.sicap.cloud.dmc.setting.controllers.exception.ImageNotFoundException
2017-04-19 18:39:02.381  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configure/ios/wlan],methods=[POST]}" onto public com.sicap.protocols.models.acknowledgement.Acknowledgment com.sicap.cloud.dmc.setting.controllers.ios.IOSConfigurationController.sendWifiProfile(com.sicap.protocols.models.wlan.WLANConfiguration) throws com.sicap.protocols.exceptions.AckNotFoundException,com.sicap.protocols.exceptions.ServerErrorException
2017-04-19 18:39:02.381  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configure/ios/apn],methods=[POST]}" onto public com.sicap.protocols.models.acknowledgement.Acknowledgment com.sicap.cloud.dmc.setting.controllers.ios.IOSConfigurationController.sendApnProfile(com.sicap.protocols.models.apn.APNConfiguration) throws com.sicap.protocols.exceptions.AckNotFoundException,com.sicap.protocols.exceptions.ServerErrorException
2017-04-19 18:39:02.381  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configure/ios/vpn],methods=[POST]}" onto public com.sicap.protocols.models.acknowledgement.Acknowledgment com.sicap.cloud.dmc.setting.controllers.ios.IOSConfigurationController.sendVpnProfile(com.sicap.protocols.models.vpn.VPNConfiguration) throws com.sicap.protocols.exceptions.AckNotFoundException,com.sicap.protocols.exceptions.ServerErrorException
2017-04-19 18:39:02.381  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configure/ios/email],methods=[POST]}" onto public com.sicap.protocols.models.acknowledgement.Acknowledgment com.sicap.cloud.dmc.setting.controllers.ios.IOSConfigurationController.sendEmailProfile(com.sicap.protocols.models.email.EmailConfiguration) throws com.sicap.protocols.exceptions.AckNotFoundException,com.sicap.protocols.exceptions.ServerErrorException
2017-04-19 18:39:02.381  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configure/ios/all],methods=[POST]}" onto public com.sicap.protocols.models.acknowledgement.Acknowledgment com.sicap.cloud.dmc.setting.controllers.ios.IOSConfigurationController.sendProfile(java.util.Set<com.sicap.protocols.models.Configuration>) throws com.sicap.cloud.dmc.setting.commons.exceptions.ErrorException,com.sicap.protocols.exceptions.AckNotFoundException,com.sicap.protocols.exceptions.ServerErrorException
2017-04-19 18:39:02.382  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configure/data/],methods=[POST]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.setting.controllers.SendSettingController.data(com.sicap.cloud.dmc.setting.entity.SettingAPN,java.lang.String)
2017-04-19 18:39:02.383  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configure/mms/],methods=[POST]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.setting.controllers.SendSettingController.mms(com.sicap.cloud.dmc.setting.entity.SettingAPN)
2017-04-19 18:39:02.383  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configure/wap/],methods=[POST]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.setting.controllers.SendSettingController.wap(com.sicap.cloud.dmc.setting.entity.SettingAPN)
2017-04-19 18:39:02.383  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configure/wlan/],methods=[POST]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.setting.controllers.SendSettingController.wlan(com.sicap.cloud.dmc.setting.entity.SettingWlan)
2017-04-19 18:39:02.383  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/send/mms/],methods=[POST]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.xms.controllers.MMSController.sendMMS(com.sicap.cloud.dmc.xms.entity.MMSContent)
2017-04-19 18:39:02.384  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/send/setting/],methods=[POST]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.xms.controllers.SMSController.sendComplexSMS(com.sicap.cloud.dmc.setting.entity.SimpleSMS)
2017-04-19 18:39:02.384  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/send/sms/],methods=[POST]}" onto public com.sicap.cloud.dmc.setting.entity.Status com.sicap.cloud.dmc.xms.controllers.SMSController.sendBasicSMS(com.sicap.cloud.dmc.setting.entity.SimpleSMS)
2017-04-19 18:39:02.385  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/ios/profile/{uuid}],methods=[GET],produces=[application/x-apple-aspen-config]}" onto public org.springframework.http.ResponseEntity<byte[]> com.sicap.protocols.ios.controllers.IosProfileController.getTemplate(java.lang.String) throws java.lang.Exception
2017-04-19 18:39:02.386  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/ios/ack/{UUID}],methods=[GET],produces=[application/json]}" onto public com.sicap.protocols.models.acknowledgement.Acknowledgment com.sicap.protocols.ios.controllers.AckController.getAck(java.lang.String) throws com.sicap.protocols.exceptions.AckNotFoundException
2017-04-19 18:39:02.387  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2017-04-19 18:39:02.388  INFO 16126 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2017-04-19 18:39:02.407  INFO 16126 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-04-19 18:39:02.407  INFO 16126 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-04-19 18:39:02.420  INFO 16126 --- [           main] .m.m.a.ExceptionHandlerExceptionResolver : Detected @ExceptionHandler methods in IOSProfileExceptionTranslator
2017-04-19 18:39:02.436  INFO 16126 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-04-19 18:39:02.552  INFO 16126 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-04-19 18:39:02.609  INFO 16126 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 9000 (http)
2017-04-19 18:39:02.614  INFO 16126 --- [           main] com.sicap.cloud.dmc.DmcCloudApplication  : Started DmcCloudApplication in 5.461 seconds (JVM running for 9.703)`

but when i tried to connect to "Swisscome" (a swiss mobile operator). i can connect to the server. But it pops out the following problems..... I dont know why.

`2017-04-19 18:40:39,459 [Tester.Session.0] DEBUG c.c.smpp.impl.DefaultSmppSession - Unbind/close was requested, ignoring exception thrown: {}
java.nio.channels.ClosedChannelException: null
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:84) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) ~[netty-3.9.6.Final.jar:na]
	at com.cloudhopper.smpp.channel.SmppSessionLogger.handleDownstream(SmppSessionLogger.java:111) ~[classes/:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.Channels.write(Channels.java:704) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.Channels.write(Channels.java:671) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248) ~[netty-3.9.6.Final.jar:na]
	at com.cloudhopper.smpp.impl.DefaultSmppSession.sendRequestPdu(DefaultSmppSession.java:532) ~[classes/:na]
	at com.cloudhopper.smpp.impl.DefaultSmppSession.sendRequestAndGetResponse(DefaultSmppSession.java:464) ~[classes/:na]
	at com.cloudhopper.smpp.impl.DefaultSmppSession.bind(DefaultSmppSession.java:334) ~[classes/:na]
	at com.cloudhopper.smpp.impl.DefaultSmppClient.doBind(DefaultSmppClient.java:215) ~[classes/:na]
	at com.cloudhopper.smpp.impl.DefaultSmppClient.bind(DefaultSmppClient.java:196) ~[classes/:na]
	at com.cloudhopper.smpp.demo.ClientMain.main(ClientMain.java:85) ~[test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) ~[idea_rt.jar:na]
2017-04-19 18:40:39,459 [main] ERROR c.c.smpp.demo.ClientMain - 
com.cloudhopper.smpp.type.SmppChannelException: null
	at com.cloudhopper.smpp.impl.DefaultSmppSession.sendRequestPdu(DefaultSmppSession.java:537) ~[classes/:na]
	at com.cloudhopper.smpp.impl.DefaultSmppSession.sendRequestAndGetResponse(DefaultSmppSession.java:464) ~[classes/:na]
	at com.cloudhopper.smpp.impl.DefaultSmppSession.bind(DefaultSmppSession.java:334) ~[classes/:na]
	at com.cloudhopper.smpp.impl.DefaultSmppClient.doBind(DefaultSmppClient.java:215) ~[classes/:na]
	at com.cloudhopper.smpp.impl.DefaultSmppClient.bind(DefaultSmppClient.java:196) ~[classes/:na]
	at com.cloudhopper.smpp.demo.ClientMain.main(ClientMain.java:85) ~[test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
Caused by: java.nio.channels.ClosedChannelException: null
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:84) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) ~[netty-3.9.6.Final.jar:na]
	at com.cloudhopper.smpp.channel.SmppSessionLogger.handleDownstream(SmppSessionLogger.java:111) ~[classes/:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.Channels.write(Channels.java:704) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.Channels.write(Channels.java:671) ~[netty-3.9.6.Final.jar:na]
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248) ~[netty-3.9.6.Final.jar:na]
	at com.cloudhopper.smpp.impl.DefaultSmppSession.sendRequestPdu(DefaultSmppSession.java:532) ~[classes/:na]
	... 10 common frames omitted
2017-04-19 18:40:39,460 [main] INFO  c.c.smpp.demo.ClientMain - Shutting down client bootstrap and executors...
2017-04-19 18:40:39,467 [main] INFO  c.c.smpp.demo.ClientMain - Done. Exiting

Process finished with exit code 0`

 Since Swisscom is a large mobile operator in Swiss. so if this cannot work..... we have to drop this library, and to find another one, which means almost 2 months of work is a waste.......

Any help will be appreciated.

Thank you!

**Comment by stela** [comment]
I've successfully used this library together with Swisscom's "SMS LA (Large Account)", is this the offer you use?

Please check:
* That you're not exceeding the global client TCP connection count, it's fairly low (5 I believe)
* Not sure about this, but use only bind_transmitter and not bind_transciever if you're only sending messages
* Make sure the bind-request fills in the correct fields for both "username"/password (system_id/password)
* Make sure you ordered an SMPP interface (not UCP)
* Make sure that if, applicable, your IP addresses are whitelisted for the account you're using
* Read the "tiny letters" at the start of the documentation, rest appears copy-pasted from the regular SMPP specs.

And once you're past the bind, if you want to use non-UCS-2 encodings, make sure the encodings match what you're sending (verify if it's ISO-8859-1/ISO-8859-15 by sending a euro sign/currency-sign/cedilla e.g.) For me using ISO-8859-15 and setting submit_sm.data_encoding=0 allowed use of € (euro) correctly. I was never able to use GSM-03.38 directly.
