### ISSUE TITLE
Occasional error when attempting to reconnect

### ISSUE THREAD

**Issue by tester5** [twitter/cloudhopper-smpp#25]
We receive this error occasionally when we attempt to reconnect to the SMSC in the event of a connection error or lost session connection.

Has anyone seen this issue before and know if there is a fix for it? See below:

[SMPPMainThread] INFO com.cloudhopper.smpp.impl.DefaultSmppSession - send PDU: ...
[SMPPMainThread] INFO com.cloudhopper.smpp.impl.DefaultSmppSession - write bytes: ...
[SMPPMainThread] ERROR smpp.SMPP - Unexpected close occurred...
[SMPPMainThread] INFO com.cloudhopper.smpp.impl.DefaultSmppSession - Session channel is already closed, not going to unbind
[SMPPMainThread] ERROR smpp.SMPP - Exception: 
java.lang.IllegalStateException: await*() in I/O thread causes a dead lock or sudden performance drop. Use addListener() instead or call await*() from a different thread.
    at org.jboss.netty.channel.DefaultChannelFuture.checkDeadLock(DefaultChannelFuture.java:343)
    at org.jboss.netty.channel.DefaultChannelFuture.await0(DefaultChannelFuture.java:307)
    at org.jboss.netty.channel.DefaultChannelFuture.await(DefaultChannelFuture.java:248)
    at com.cloudhopper.smpp.impl.DefaultSmppClient.createConnectedChannel(DefaultSmppClient.java:248)
    at com.cloudhopper.smpp.impl.DefaultSmppClient.doOpen(DefaultSmppClient.java:212)
    at com.cloudhopper.smpp.impl.DefaultSmppClient.bind(DefaultSmppClient.java:181)
    at smpp.SMPP$ClientSessionTask.reconnect(SMPP.java:174)
    at smpp.SMPP$ClientSessionTask$ClientSmppSessionHandler.fireChannelUnexpectedlyClosed(SMPP.java:284)
    at com.cloudhopper.smpp.impl.DefaultSmppSession.fireChannelClosed(DefaultSmppSession.java:688)
    at com.cloudhopper.smpp.channel.SmppSessionWrapper.channelClosed(SmppSessionWrapper.java:88)
    at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:113)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:565)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:793)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.cleanup(FrameDecoder.java:489)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.channelClosed(FrameDecoder.java:372)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:93)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:565)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:793)
    at com.cloudhopper.smpp.channel.SmppSessionLogger.handleUpstream(SmppSessionLogger.java:104)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:565)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:793)
    at com.cloudhopper.smpp.channel.SmppSessionThreadRenamer.handleUpstream(SmppSessionThreadRenamer.java:59)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:565)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:793)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.channelClosed(SimpleChannelUpstreamHandler.java:215)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:93)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:565)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
    at org.jboss.netty.channel.Channels.fireChannelClosed(Channels.java:476)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:730)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:89)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:662)
Session 0 is not bound, binding or open. Attempting to reconnect...
[SmppSessionMonitorThread] INFO com.cloudhopper.smpp.impl.DefaultSmppSession - Session channel is already closed, not going to unbind
[SmppSessionMonitorThread] INFO com.cloudhopper.smpp.impl.DefaultSmppSession - sync send PDU: ...
[SmppSessionMonitorThread] INFO com.cloudhopper.smpp.impl.DefaultSmppSession - write bytes: ...
Enquire link to keep session 0 alive.
[SMPPMainThread] INFO com.cloudhopper.smpp.impl.DefaultSmppSession - read bytes: ...
[SMPPMainThread] INFO com.cloudhopper.smpp.impl.DefaultSmppSession - received PDU: ...
[SmppSessionMonitorThread] INFO smpp.SMPP - Session reconnected!

**Comment by jjlauer** [comment]
Closing this issue for now -- unless the latest beta build using Netty4 still has the question open.
