### ISSUE TITLE
Netty4 deadlock - DefaultSmppClient#destroy vs #bind

### ISSUE THREAD

**Issue by krasa** [twitter/cloudhopper-smpp#92]
I was building a new performance test https://github.com/krasa/cloudhopper-smpp/commit/b458153ad8061968b777166999b2d87cb02d38b7 and when I call DefaultSmppClient#destroy while other threads are binding, then it will never shutdown. (reproducible in majority of runs, when the server is not running)

Netty 3 did not have this problem ( https://github.com/krasa/cloudhopper-smpp/commit/fd78835d74992e476b5a584f5b8bd65cc4947dd8 ). 

```
"pool-1-thread-10" prio=6 tid=0x0000000011d8a800 nid=0xe34 in Object.wait() [0x000000001302f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007ace27578> (a io.netty.channel.DefaultChannelPromise)
	at java.lang.Object.wait(Object.java:503)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:286)
	- locked <0x00000007ace27578> (a io.netty.channel.DefaultChannelPromise)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:135)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:28)
	at com.cloudhopper.smpp.impl.DefaultSmppClient.createConnectedChannel(DefaultSmppClient.java:311)
	at com.cloudhopper.smpp.impl.DefaultSmppClient.doOpen(DefaultSmppClient.java:234)
	at com.cloudhopper.smpp.impl.DefaultSmppClient.bind(DefaultSmppClient.java:203)
	at com.cloudhopper.smpp.demo.perftest.PerformanceClientMain2$ClientSessionTask.run(PerformanceClientMain2.java:218)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jjlauer** [comment]
Sometimes I think Netty4 should have taken a new project name due to its massive backwards incompatibility. Have you dug into what you think the underlying problem is?

**Comment by krasa** [comment]
It looks like a netty bug to me. I will dig deeper if you do not have a time.

**Comment by krasa** [comment]
testcase:
```
public class Netty4Deadlock {

    private static final Logger logger = LoggerFactory.getLogger(Netty4Deadlock.class);

    public static void main(String[] args) throws UnrecoverablePduException, SmppChannelException, InterruptedException, SmppTimeoutException {
        DefaultChannelGroup channels = new DefaultChannelGroup(GlobalEventExecutor.INSTANCE);
        Bootstrap clientBootstrap = new Bootstrap();
        NioEventLoopGroup workerGroup = new NioEventLoopGroup();
        clientBootstrap.group(workerGroup);
        clientBootstrap.channel(NioSocketChannel.class);
        clientBootstrap.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000);
        clientBootstrap.handler(new LoggingHandler());

        ChannelFuture connectFuture = clientBootstrap.connect(new InetSocketAddress("localhost", 5000));

        destroy(channels, workerGroup);

        logger.info("deadlock here:");
        connectFuture.awaitUninterruptibly();
        logger.info("done");
    }

    private static void destroy(DefaultChannelGroup channels, NioEventLoopGroup workerGroup) {
        logger.info("destroy");
        channels.close().awaitUninterruptibly();

        workerGroup.shutdownGracefully();

        try {
            // Wait until all threads are terminated.
            workerGroup.terminationFuture().sync();
        } catch (InterruptedException e) {
            logger.warn("Thread interrupted closing executors.", e);
        }
    }
}
```
